authors:
  L1NINE:
    name: L1NINE
    description: 作者
    avatar: https://github.com/L1NINE.png
  
  mybear123:
    name: mybear123
    description: 作者
    avatar: https://github.com/mybear123.png

  光钻:
    name: 光钻
    description: 作者
    avatar: https://github.com/mybear123.png
  
  梦归云帆:
    name: 梦归云帆
    description: 作者
    avatar: https://github.com/Puiching-Memory.png
  
  我可以:
    name: 我可以
    description: 作者
    avatar: https://github.com/qq187.png

  小小登下士:
    name: 小小登下士
    description: 作者
    avatar: https://github.com/mybear123.png